FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine AS final
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

