version: '3.8'
services:
  frontend:
    build: .
    image: projeto-casa-control-frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
